apiVersion: v1
kind: Namespace
metadata:
  name: alpha


--- 
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-recreate-deployment
spec:
 strategy:
  type: Recreate
 replicas: 1
 selector:
   matchLabels:
    app: app1-nginx
 template:
   metadata:
    name: app1-pod
    labels:
     app: app1-nginx
   spec:
     containers:
     - name: app1-nginx
       image: nagpcontainerregistry.azurecr.io/dockerdeploy:latest
       env:
       - name: Application_Name
         valueFrom:
            secretKeyRef:
              name: app1-secret
              key: Application_Username
       - name: Application_Password
         valueFrom:
            secretKeyRef:
              name: app1-secret
              key: Application_Password
       - name: Application_ConnectionString
         valueFrom:
            configMapKeyRef:
              name: app1-configmap
              key: Application_ConnectionString
       - name: Application_Environment
         value: alpha
       ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-clusterip-service
  labels:
    app: app1-nginx
spec:
  type: ClusterIP
  selector:
    app: app1-nginx
  ports:
    - port: 80
      targetPort: 80